[package]
name = "kasbah-daemon"
version.workspace = true
edition.workspace = true

[dependencies]
kasbah-kernel = { path = "../kasbah-kernel" }
axum = "0.7"
tokio = { version = "1", features = ["rt-multi-thread", "macros"] }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
tower-http = { version = "0.5", features = ["cors"] }
rusqlite = { version = "0.31", features = ["bundled"] }
getrandom = "0.2"

base64 = "0.22"
